name: Install Amadla CLI

on:
  workflow_call:

jobs:
    install-amadla-cli:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
            uses: actions/checkout@v3

        - name: Install Amadla CLI
